eval "$(nodenv init -)"
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
# export NODE_OPTIONS=--openssl-legacy-provider

alias vim="nvim"
alias v="nvim"

alias dcu="docker compose up -d --build"
function dce() {
  docker compose exec $1 bash
}

alias zsh-source="source ~/.zshrc"

export PATH=$PATH:~/.bin:~/.local/share/nvim/mason/bin
