
name: pienter__config
windows:
  - tabs:
    - title: pienter__config
      layout:
        split_direction: horizontal
        panes: 
          - cwd: /Users/korneel/dev/projects/pienter/config/
            commands:
              - exec: v .
          - split_direction: vertical
            panes:
              - cwd: /Users/korneel/dev/projects/pienter/config/
              - cwd: /Users/korneel/dev/projects/pienter/config/
      color: blue
        