zstyle :plugin:fast-syntax-highlighting theme "catppuccin-mocha"
typeset -g FAST_THEME_NAME="catppuccin-mocha"
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochadefault]:=fg=#cdd6f4}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochaunknown-token]:=fg=#f38ba8,bold}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochareserved-word]:=fg=#cba6f7}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochaalias]:=fg=#89b4fa}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochasuffix-alias]:=fg=#89b4fa}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochabuiltin]:=fg=#cba6f7}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochafunction]:=fg=#89b4fa}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochacommand]:=fg=#89b4fa}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochaprecommand]:=fg=#cba6f7}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochacommandseparator]:=fg=#94e2d5}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochahashed-command]:=fg=#89b4fa}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochapath]:=fg=#f5e0dc}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochapath_pathseparator]:=fg=#f5e0dc}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochaglobbing]:=fg=#f5c2e7}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochaglobbing-ext]:=none}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochahistory-expansion]:=none}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochasingle-hyphen-option]:=fg=#94e2d5}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochadouble-hyphen-option]:=fg=#94e2d5}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochaback-quoted-argument]:=fg=#94e2d5}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochasingle-quoted-argument]:=fg=#a6e3a1}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochadouble-quoted-argument]:=fg=#a6e3a1}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochadollar-quoted-argument]:=fg=#a6e3a1}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochaback-or-dollar-double-quoted-argument]:=fg=#fab387}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochaback-dollar-quoted-argument]:=fg=#fab387}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochaassign]:=none}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mocharedirection]:=fg=#94e2d5}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochacomment]:=fg=#6c7086}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochavariable]:=fg=#fab387}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochamathvar]:=fg=#f5c2e7}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochamathnum]:=fg=#fab387}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochamatherr]:=fg=#f38ba8,bold}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochaassign-array-bracket]:=none}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochafor-loop-variable]:=fg=#cdd6f4}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochafor-loop-number]:=fg=#fab387}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochafor-loop-operator]:=fg=#89b4fa}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochafor-loop-separator]:=fg=#89b4fa}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochaexec-descriptor]:=none}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochahere-string-tri]:=fg=#bac2de}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochahere-string-text]:=fg=#bac2de}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochahere-string-var]:=fg=#bac2de}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochasecondary]:=}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochacase-input]:=fg=#fab387}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochacase-parentheses]:=fg=#9399b2}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochacase-condition]:=fg=#b4befe}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochacorrect-subtle]:=fg=#b4befe}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochaincorrect-subtle]:=fg=#eba0ac}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochasubtle-separator]:=none}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochasubtle-bg]:=none}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochapath-to-dir]:=fg=#f5e0dc}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochapaired-bracket]:=bold}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochabracket-level-1]:=fg=#f38ba8}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochabracket-level-2]:=fg=#f9e2af}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochabracket-level-3]:=fg=#74c7ec}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochaglobal-alias]:=fg=#89b4fa}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochasubcommand]:=fg=#74c7ec}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochasingle-sq-bracket]:=fg=#f9e2af}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochadouble-sq-bracket]:=fg=#f9e2af}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochadouble-paren]:=fg=#a6e3a1}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochaoptarg-string]:=fg=#a6e3a1}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mochaoptarg-number]:=fg=#fab387}
: ${FAST_HIGHLIGHT_STYLES[catppuccin-mocharecursive-base]:=fg=#cdd6f4}
